export const SEARCH_HUB_LOGO_SRC = "/icons/saveroute_logo.png";
export const SEARCH_HUB_LOGO_WIDTH = 682;
export const SEARCH_HUB_LOGO_HEIGHT = 67;
export const SEARCH_HUB_LOGO_DISPLAY_HEIGHT = 25;
export const SEARCH_HUB_LOGO_DISPLAY_WIDTH = Math.round(
  SEARCH_HUB_LOGO_WIDTH * (SEARCH_HUB_LOGO_DISPLAY_HEIGHT / SEARCH_HUB_LOGO_HEIGHT),
);
